-- Backfill cronológico do histórico de desenvolvimento (dev_tracker_log)
-- Datas baseadas nas migrations e planos versionados do projeto.
-- Executar no SQL Editor do Supabase APÓS a migration db/migrations/20260830130000_dev_tracker_log.sql
-- Seguro para reexecução: limpa apenas os lançamentos anteriores a 2026-08-30.

DELETE FROM public.dev_tracker_log WHERE occurred_on < '2026-08-30';

INSERT INTO public.dev_tracker_log (occurred_on, system_name, title, description, change_type, hours) VALUES
-- ===== 2025 =====
('2025-10-15','infraestrutura','Base do registro de desenvolvimento','Criação da tabela dev_tracker e carga inicial das funcionalidades por sistema.','novo',3),
('2025-10-15','escalas','Mapa de elegibilidade dos corretores','Estrutura de elegibilidade por local e marcação de alocação manual na geração de escalas.','novo',6),
('2025-10-15','estoque','Estrutura inicial do módulo de Estoque','Tabelas de materiais, locais, saldos, movimentações e solicitações, com RLS e políticas de recebimento.','novo',16),
('2025-10-15','estoque','Vínculo de usuários a unidades e setores','Controle de quais unidades/setores cada usuário do estoque enxerga e movimenta.','novo',5),
('2025-10-15','ferias','Afastamentos e períodos de gozo','Cadastro de afastamentos, períodos de gozo e períodos quitados no módulo de Férias.','novo',10),
('2025-10-15','ferias','Venda de férias por quinzena','Campos de quinzena de venda, envio ao contador e backfill dos registros existentes.','novo',7),
('2025-10-15','ferias','Auditoria e status automático de férias','Triggers de auditoria, reconciliação determinística de status e correção de status prematuro.','correcao',8),
('2025-10-15','infraestrutura','Correções de segurança em RLS','Revisão geral de políticas RLS e limpeza de vínculos inativos de corretores.','correcao',5),
('2025-10-20','escalas','Ajustes na geração de escalas','Correções na distribuição de plantões e regras de rodízio.','ajuste',4),
('2025-11-02','vendas','Ajustes no módulo de Vendas','Correções em cadastros e indicadores do sistema de vendas.','ajuste',3),
('2025-11-20','escalas','Rodízio de sábados e filas por local','Sincronização das filas de rodízio por local e da fila de sábados.','novo',9),
('2025-11-21','escalas','Correções da fila de rodízio','Ajustes de sincronização de status e reprocessamento das filas após alocação.','correcao',6),
('2025-11-30','vendas','Metas de equipes e corretores','Estrutura de metas mensais por corretor e por equipe.','novo',5),
('2025-12-09','vendas','Propostas e vendas com participantes','Registro de propostas, vendas e corretores participantes com rateio.','novo',10),
('2025-12-10','vendas','Dashboard de vendas','Indicadores de VGV, ranking de corretores e equipes.','novo',12),
('2025-12-11','vendas','Avaliações de corretores','Formulário de avaliação com cálculo automático de nota.','novo',8),
('2025-12-12','vendas','Relatórios de vendas','Relatórios por período, corretor e equipe com exportação.','novo',9),
('2025-12-13','vendas','Leads mensais','Registro de leads mensais, aproveitamento e descarte.','novo',6),
('2025-12-15','escalas','Relatórios e auditoria de escalas','Relatórios de plantões e log de auditoria do módulo.','novo',7),
('2025-12-16','infraestrutura','Perfis de usuário e papéis','Tabela de papéis separada e funções de verificação de permissão.','novo',6),
('2025-12-17','infraestrutura','Controle de acesso por sistema','Tabela system_access e funções can_view_system / can_edit_system.','novo',5),
('2025-12-20','infraestrutura','Gestão de usuários','Página de gestão de usuários com convite e alteração de papéis.','novo',8),
-- ===== 2026 =====
('2026-01-05','ferias','Calendário de férias','Visão de calendário com conflitos entre colaboradores.','novo',9),
('2026-01-06','ferias','Folgas e créditos','Controle de folgas, créditos, escala e perdas.','novo',10),
('2026-01-07','ferias','Formulário anual de férias','Coleta anual de preferências de período por colaborador.','novo',7),
('2026-01-08','ferias','Estrutura organizacional','Unidades, setores, equipes, chefes e substitutos.','novo',8),
('2026-01-10','ferias','Feriados e configurações','Cadastro de feriados e parâmetros gerais do módulo.','novo',4),
('2026-01-11','ferias','Relatórios de férias','Relatórios consolidados e exportação.','novo',5),
('2026-01-14','ferias','Correções gerais no módulo de Férias','Diversos ajustes de validação, status e cálculo de períodos.','correcao',9),
('2026-01-15','ferias','Dados sensíveis do colaborador','Separação de dados sensíveis em tabela própria com RLS restrita.','novo',4),
('2026-01-21','estoque','Notificações de estoque','Alertas de estoque mínimo e pendências de solicitação.','novo',5),
('2026-01-23','estoque','Gestores de estoque','Definição de gestores por local e permissões associadas.','novo',3),
('2026-01-24','escalas','Observações e travas de escala','Bloqueio de escalas publicadas e observações por escala.','novo',4),
('2026-02-04','vendas','Ajustes de relatórios de vendas','Correções de agregação e filtros por período.','correcao',4),
('2026-02-07','infraestrutura','Auditoria por módulo','Log de auditoria unificado com descrição humanizada.','novo',6),
('2026-02-12','escalas','Validação pós-geração de escalas','Validador que aponta corretores sem alocação e conflitos.','novo',7),
('2026-02-14','ferias','Correções de conflitos de férias','Ajuste na detecção de conflitos entre setores e substitutos.','correcao',5),
('2026-02-17','estoque','Movimentações e saldos','Ajustes no cálculo de saldos e histórico de movimentações.','correcao',5),
('2026-02-20','infraestrutura','Guardas de segurança em funções','Proteção contra valores nulos e políticas de exclusão.','correcao',4),
('2026-05-05','estoque','Categorias de materiais','Cadastro de categorias e backfill dos materiais existentes.','novo',5),
('2026-05-06','infraestrutura','Correções de achados de segurança','Ajustes de políticas apontadas pelo scanner de segurança.','correcao',4),
('2026-05-08','ferias','Triggers de auditoria de férias','Registro automático de alterações em férias.','novo',4),
('2026-05-16','ferias','Premiações','Módulo de premiações com atesto, ordem e PDF.','novo',12),
('2026-05-17','infraestrutura','Guardas de autorização em RPCs','Verificação de permissão dentro das funções do banco.','correcao',5),
('2026-05-22','estoque','Integração com estrutura de Férias','Uso das unidades/setores de Férias no Estoque.','atualizacao',4),
('2026-06-15','ferias','Correção do motivo de perda de folga','Ajuste da restrição de motivos aceitos.','correcao',2),
('2026-06-24','estoque','Placas: categoria e código opcional','Cadastro de placas com código opcional e categoria própria.','novo',6),
('2026-06-25','estoque','Confirmação de recebimento','RPC de confirmação de recebimento e estados da solicitação.','novo',6),
('2026-07-02','escalas','Validação de datas específicas do período','Triggers que impedem configurações fora do intervalo do período e correção do diálogo do Nammos.','correcao',6),
('2026-07-08','estoque','Atributos de placas','Tipo de uso e medidas dos materiais do tipo placa.','novo',4),
('2026-07-11','estoque','Reaproveitamento de código de placa','Liberação e reuso de códigos de placas retiradas ou perdidas.','novo',5),
('2026-07-17','despesas','Despesas Fase 2 - Lançamentos e calendário','Lançamentos, pagamentos e calendário de despesas.','novo',16),
('2026-07-18','despesas','Despesas Fase 3 - Imóveis e veículos','Cadastro de imóveis, veículos, encargos e documentos.','novo',14),
('2026-07-19','despesas','Despesas Fase 4 - Recorrências','Recorrências com geração automática de parcelas.','novo',12),
('2026-07-20','despesas','Notificações em tempo real','Notificações de vencimento com realtime e preferências.','novo',6),
('2026-07-21','infraestrutura','search_path fixo nas funções','Correção de search_path mutável nas funções do banco.','correcao',3),
('2026-07-22','despesas','Auditoria humanizada de despesas','Log de auditoria com descrição legível das alterações.','novo',5),
('2026-07-23','despesas','Despesas Fase 5 - Status e limites','Status quitado/gimob, proteção de credenciais e limites de repasse.','novo',10),
('2026-07-25','infraestrutura','Restrição de escopo do perfil Admin','Admin deixa de acessar áreas exclusivas do super admin.','correcao',5),
('2026-07-28','estoque','Permissão de edição de placas','Usuários com permissão de edição passam a manipular placas.','correcao',3),
('2026-07-29','despesas','Referências obrigatórias no lançamento','Pelo menos uma referência (pessoa, imóvel, pasta ou venda) por lançamento.','novo',6),
('2026-07-30','despesas','Centros de custo com negação padrão','Acesso a centros de custo passa a ser explicitamente concedido.','correcao',4),
('2026-07-31','despesas','Valor opcional e múltiplas referências','Valor total deixa de ser obrigatório, subcategoria removida e múltiplas referências no lançamento.','atualizacao',7),
('2026-07-31','despesas','Diálogos ajustados à tela','Padronização de altura máxima e rolagem interna dos diálogos.','correcao',4),
('2026-08-01','despesas','Cadastro de pessoas e papéis','CRUD de pessoas com papéis padronizados e validação de CPF/CNPJ.','novo',8),
('2026-08-02','ferias','Registro de eventos de férias','RPC de auditoria detalhada das alterações de férias.','novo',4),
('2026-08-04','despesas','Índice de duplicidade de pessoas','Bloqueio de CPF/CNPJ repetido.','correcao',2),
('2026-08-05','despesas','Detecção de imóveis duplicados','Índice e alerta de possível duplicidade de imóveis.','correcao',3),
('2026-08-06','infraestrutura','Proteção do papel super admin','Guarda contra escalonamento de privilégios em user_roles.','correcao',3),
('2026-08-07','despesas','Repasses: beneficiários','Cadastro de beneficiários do repasse com rateio.','novo',9),
('2026-08-07','vendas','Desempate em propostas por corretor','Empate de propostas resolvido por convertidas e depois por nome.','ajuste',2),
('2026-08-08','despesas','Limite por beneficiário','Limite de valor por beneficiário no repasse.','novo',5),
('2026-08-09','despesas','Contas de repasse','Contas bancárias vinculadas ao repasse.','novo',4),
('2026-08-11','despesas','Unicidade dos itens de repasse','Bloqueio de lançamento duplicado no mesmo repasse.','correcao',3),
('2026-08-12','despesas','Veículos como aba própria','Separação de veículos em página independente com permissões.','atualizacao',6),
('2026-08-12','ferias','Cancelamento do 2º período','Permite cancelar o segundo período mantendo o registro válido.','novo',5),
('2026-08-12','despesas','Busca, ordenação e paginação em Recorrências','Busca sem acento, filtros, ordenação e paginação configurável.','novo',5),
('2026-08-12','despesas','Busca do calendário e falsas duplicidades','Busca em múltiplos campos e refino do alerta de duplicidade.','correcao',5),
('2026-08-12','despesas','Propagação de alterações na recorrência','Aviso para aplicar a alteração às parcelas seguintes da série.','novo',7),
('2026-08-13','despesas','Pagamentos aos beneficiários','Registro e conciliação dos pagamentos do repasse.','novo',6),
('2026-08-14','despesas','Bens permanentes','Nova página de patrimônio nos moldes de imóveis.','novo',12),
('2026-08-14','ferias','Confirmação de alterações em férias','Diálogo mostrando antes/depois antes de salvar.','novo',6),
('2026-08-15','estoque','Entrada de saldos para supervisor','Supervisores passam a registrar entradas, ajustes e saídas.','correcao',4),
('2026-08-15','despesas','Calendário e recorrências por veículo','Abas filtradas pelos gastos de cada veículo.','novo',7),
('2026-08-21','estoque','Solicitações sem movimentação','Coluna de solicitante, trava na entrega e avisos no detalhe.','correcao',5),
('2026-08-22','estoque','Acesso de apoio ao estoque','Restauração das ações de entrada, ajuste e saída para o perfil de apoio.','correcao',4),
('2026-08-23','ferias','Período histórico da venda','Correção da persistência da quinzena de venda em correções históricas.','correcao',6),
('2026-08-23','estoque','WITH CHECK em notificações','Correção de política RLS de atualização.','correcao',1),
('2026-08-24','estoque','Estoque máximo e aba Reposição','Campo de estoque máximo e painel do que falta para completar, com PDF.','novo',9),
('2026-08-25','ferias','Histórico de admissão e desligamento','Vínculos do colaborador com data de demissão e reativação.','novo',8),
('2026-08-26','estoque','RLS na saída de placa para imóvel','Correção do erro de política ao registrar saída de placa.','correcao',3),
('2026-08-27','despesas','Itens do repasse agrupados por imóvel','Imóvel adicionado uma vez, com créditos e débitos dentro do bloco.','atualizacao',8),
('2026-08-28','despesas','Remoção de imóvel do repasse','Exclusão com confirmação, recálculo do saldo e campos de valor sem setas.','atualizacao',5),
('2026-08-29','despesas','Veículos: encargos e calendário vazio','Aceite de veículo como referência, gerador defensivo, mensagens em português e visão anual do calendário.','correcao',7);
